# Dependencies
markdown:        kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty
  #relative_permalinks: true

# Setup
title:            Namratha Vasu 
tagline:          ''
description:      "Community, Collaboration, and Creativity."
url:              http://hyde.getpoole.com
baseurl:          "https://vasunam.github.io/"

author:
  name:           'Namratha Vasu'
  url:            https://twitter.com/Namratha_Vasu

    #paginate:         5

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
