baseURL = 'https://vasunam.github.io/'
languageCode = 'en-us'
title = 'Namratha Vasu'
theme = 'victorian'

# Enable syntax highlighting
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = false
  style = 'github'

[markup.goldmark.renderer]
  unsafe = true

# Main menu
[menu]
  [[menu.main]]
    name = 'About Me'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'Thoughts'
    url = '/posts/'
    weight = 20

# Custom parameters
[params]
  description = "Namratha Vasu - AI-native Product Manager"
  author = "Namratha Vasu"
  twitterUrl = 'https://x.com/Namratha_Vasu'
  enableGoogleAnalytics = true
  googleAnalyticsID = 'G-EX1XWRKFQR'
  copyright = "© 2025 | Created with ❤️"
